CREATE CONSTRAINT unique_junction IF NOT EXISTS
FOR (n:JUNCTION)
REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT unique_uturn IF NOT EXISTS
FOR (n:UTURN)
REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT unique_place IF NOT EXISTS
FOR (n:IMPORTANT_PLACE)
REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT unique_start IF NOT EXISTS
FOR (n:START)
REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT unique_one IF NOT EXISTS
FOR ()-[r:ONE_WAY]-()
REQUIRE r.name IS UNIQUE;

CREATE CONSTRAINT unique_two IF NOT EXISTS
FOR ()-[r:TWO_WAY]-()
REQUIRE r.name IS UNIQUE;